version: "3.9"

services:
  app:
    build: .
    container_name: pruebaNT_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
